### ISSUE TITLE
反饋

### ISSUE THREAD

**Issue by forgot64** [R-a-s-c-a-l/Lenovo-Yoga-C740-14IML#1]
替換了自己的無線網卡驅動測試了兩天。
bigsur下基本完美，airdrop，睡眠，icloud正常。之前用了一年多thrrip的bigsur版，您的版本體驗優點：
1。機型macbookpro15.2比我原先的16.2速度快，我用hacktool看之前是32位，現在是64位，不知有沒有關係。
2。開機順暢不閃屏，之前的版本閃一下，而且5%的概率黑屏，需要先合蓋再開才顯示桌面。
3。oc0.83驅動更新，之前的0.69有仿冒驅動大版本更新翻車
發現的問題：安裝後觸摸屏可用，關上蓋子再打開後觸摸失效，之前我用的版本正好相反，安裝後沒有觸摸，關上再打開屏幕才有。不過對我來說無所謂，因為也不是多點觸摸，本身使用感受太差。

monterey下問題比較多，能引導，跑碼8-15分鐘才能進入安裝界面，期間頻繁出現：failed lookup:name=com.apple.logd
flags=0x9,requestor=displaypolicyd,error=3,no such process進入安裝界面無法找到內置硬盤。
我嘗試過：
1.開關xhci和usbport選項，無效。
2.ocat重新升級一下整體oc，無效。
3.hfsplus替換成openhfs，無效。
4.先安裝bigsur，再下載原版monterey.iso，才安裝成功，但每次需要8分鐘才能進桌面，設置中很多選項點擊後無響應，整體運行反應慢半拍，有的軟件無法運行，又返回了bigsur。之前用thrrip的也無法安裝monterey，引導一直出現mach reboot錯誤。

決定留在bigsur養老了，期待您出ventura OC再進行測試。

**Comment by yangyanch** [comment]
> 替換了自己的無線網卡驅動測試了兩天。 bigsur下基本完美，airdrop，睡眠，icloud正常。之前用了一年多thrrip的bigsur版，您的版本體驗優點： 1。機型macbookpro15.2比我原先的16.2速度快，我用hacktool看之前是32位，現在是64位，不知有沒有關係。 2。開機順暢不閃屏，之前的版本閃一下，而且5%的概率黑屏，需要先合蓋再開才顯示桌面。 3。oc0.83驅動更新，之前的0.69有仿冒驅動大版本更新翻車 發現的問題：安裝後觸摸屏可用，關上蓋子再打開後觸摸失效，之前我用的版本正好相反，安裝後沒有觸摸，關上再打開屏幕才有。不過對我來說無所謂，因為也不是多點觸摸，本身使用感受太差。
> 
> monterey下問題比較多，能引導，跑碼8-15分鐘才能進入安裝界面，期間頻繁出現：failed lookup:name=com.apple.logd flags=0x9,requestor=displaypolicyd,error=3,no such process進入安裝界面無法找到內置硬盤。 我嘗試過： 1.開關xhci和usbport選項，無效。 2.ocat重新升級一下整體oc，無效。 3.hfsplus替換成openhfs，無效。 4.先安裝bigsur，再下載原版monterey.iso，才安裝成功，但每次需要8分鐘才能進桌面，設置中很多選項點擊後無響應，整體運行反應慢半拍，有的軟件無法運行，又返回了bigsur。之前用thrrip的也無法安裝monterey，引導一直出現mach reboot錯誤。
> 
> 決定留在bigsur養老了，期待您出ventura OC再進行測試。

一样的电脑，同样安装bigsur（不过我没换网卡，所以安装了Intel无线驱动）。电脑合盖之后再开，电脑会黑屏（但有光），无法唤醒，不知道哪里出了问题……还有就是触摸屏没有触摸功能

**Comment by forgot64** [comment]
> 
你試一下thrrip發布的3.0oc，已經適配了ventura用了一週比較完美，這兩位大佬我都收藏了

**Comment by forgot64** [comment]
> > 替換了自己的無線網卡驅動測試了兩天。 bigsur下基本完美，airdrop，睡眠，icloud正常。之前用了一年多thrrip的bigsur版，您的版本體驗優點： 1。機型macbookpro15.2比我原先的16.2速度快，我用hacktool看之前是32位，現在是64位，不知有沒有關係。 2。開機順暢不閃屏，之前的版本閃一下，而且5%的概率黑屏，需要先合蓋再開才顯示桌面。 3。oc0.83驅動更新，之前的0.69有仿冒驅動大版本更新翻車 發現的問題：安裝後觸摸屏可用，關上蓋子再打開後觸摸失效，之前我用的版本正好相反，安裝後沒有觸摸，關上再打開屏幕才有。不過對我來說無所謂，因為也不是多點觸摸，本身使用感受太差。
> > monterey下問題比較多，能引導，跑碼8-15分鐘才能進入安裝界面，期間頻繁出現：failed lookup:name=com.apple.logd flags=0x9,requestor=displaypolicyd,error=3,no such process進入安裝界面無法找到內置硬盤。 我嘗試過： 1.開關xhci和usbport選項，無效。 2.ocat重新升級一下整體oc，無效。 3.hfsplus替換成openhfs，無效。 4.先安裝bigsur，再下載原版monterey.iso，才安裝成功，但每次需要8分鐘才能進桌面，設置中很多選項點擊後無響應，整體運行反應慢半拍，有的軟件無法運行，又返回了bigsur。之前用thrrip的也無法安裝monterey，引導一直出現mach reboot錯誤。
> > 決定留在bigsur養老了，期待您出ventura OC再進行測試。
> 
> 一样的电脑，同样安装bigsur（不过我没换网卡，所以安装了Intel无线驱动）。电脑合盖之后再开，电脑会黑屏（但有光），无法唤醒，不知道哪里出了问题……还有就是触摸屏没有触摸功能

你試一下thrrip發布的3.0oc，已經適配了ventura用了一週比較完美，這兩位大佬我都收藏了

**Comment by yangyanch** [comment]
> > > 替換了自己的無線網卡驅動測試了兩天。 bigsur下基本完美，airdrop，睡眠，icloud正常。之前用了一年多thrrip的bigsur版，您的版本體驗優點： 1。機型macbookpro15.2比我原先的16.2速度快，我用hacktool看之前是32位，現在是64位，不知有沒有關係。 2。開機順暢不閃屏，之前的版本閃一下，而且5%的概率黑屏，需要先合蓋再開才顯示桌面。 3。oc0.83驅動更新，之前的0.69有仿冒驅動大版本更新翻車 發現的問題：安裝後觸摸屏可用，關上蓋子再打開後觸摸失效，之前我用的版本正好相反，安裝後沒有觸摸，關上再打開屏幕才有。不過對我來說無所謂，因為也不是多點觸摸，本身使用感受太差。
> > > monterey下問題比較多，能引導，跑碼8-15分鐘才能進入安裝界面，期間頻繁出現：failed lookup:name=com.apple.logd flags=0x9,requestor=displaypolicyd,error=3,no such process進入安裝界面無法找到內置硬盤。 我嘗試過： 1.開關xhci和usbport選項，無效。 2.ocat重新升級一下整體oc，無效。 3.hfsplus替換成openhfs，無效。 4.先安裝bigsur，再下載原版monterey.iso，才安裝成功，但每次需要8分鐘才能進桌面，設置中很多選項點擊後無響應，整體運行反應慢半拍，有的軟件無法運行，又返回了bigsur。之前用thrrip的也無法安裝monterey，引導一直出現mach reboot錯誤。
> > > 決定留在bigsur養老了，期待您出ventura OC再進行測試。
> > 
> > 
> > 一样的电脑，同样安装bigsur（不过我没换网卡，所以安装了Intel无线驱动）。电脑合盖之后再开，电脑会黑屏（但有光），无法唤醒，不知道哪里出了问题……还有就是触摸屏没有触摸功能
> 
> 你試一下thrrip發布的3.0oc，已經適配了ventura用了一週比較完美，這兩位大佬我都收藏了

好的，谢谢提醒。不过对于这款电脑，触屏好像是个难题，都解决不了……

**Comment by R-a-s-c-a-l** [comment]
这EFI 是我给别人定制的 当时弄的时候 触摸板触摸屏都正常 且支持多指手势 这机器的 触屏中断模式我用的轮训 触摸板是Gpio 关于你们反馈的问题 只说不能用连个IOregistry 存档或者VoodooI2C的日志都没有说这些自然是没意义
